#include <stdio.h>
#include <stdlib.h>
#include <math.h>
/*
Highly divisible triangular number
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

int sasiaEpjestuesve(long long numri){
    int i, sasia = 0;
    for(i = 1; i < sqrt(numri); i++){
        if(numri % i == 0){
            (sasia) += 2;
        }
    }
    sasia += (numri % (long long)sqrt(numri) == 0);
    return sasia;
}

long long gjeneroTriangleNumbers(int i){
    long long numri = ((1 + i) * i) / 2;
    return numri;
}

int main()
{
    /*

    */
    int i = 1, sasia;
    while((sasia = sasiaEpjestuesve(gjeneroTriangleNumbers(i))) < 1000){
        i++;
    }
    printf("%d %d\n %lld\n", sasia, i, gjeneroTriangleNumbers(i));
    return 0;
}
